name: fastapi
services:
  app:
    image: fastapi
    ports:
      - 127.0.0.1:8001:8001
    network_mode: host
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql