version: '3.8'

services:
  app-fastapi-back:
    image: fastapi-back
    ports:
      - "127.0.0.1:8000:8000"
    network_mode: host
    depends_on:
      postgresql:
        condition: service_healthy

  app-fastapi:
    image: fastapi
    ports:
      - "127.0.0.1:8001:8001"
    network_mode: host
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
