# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODFhYzc4OGI2MmY1M2NhYTZmNGMzMWJmYThmYzI1MjRjMDFjNjdmYTY2NzI2Nzk2ZjZlNDRkYmQyODg4NDcwNmM4MDBiNmQzYjcyYzYyM2YwYmYyMzA0ZTU3ZDM1NmFkNDk0ZmI3YTgyMDIwNjY5OWQ5Nzk1N2JlYzMyYmU2NTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
